// JAVASCRIPT-----1)SYNCHRONOUS 2)SINGLE THREADED
// ===>EXECUTION CONTEXT--->EXECUTION ONE LINE OF CODE AT A Time
// 1)CONSOLE LOG->1
// 2)CONSOLE LOG->2
// CALL STACK AND MEMORY HEAP


// BLOCKING CODE         VS     NON BLOCKING CODE
// I)BLOCK THE FLOW OF PROGRAM    I) DOSE NOT BLOCK EXECUTION
// II)READ FILE SYNCHRONOUS             II)READ FILE ASYNCHRONOUS